### ISSUE TITLE
Add support for React 18 strict mode (WAS: Change in Record not causing re-render on initial update)

### ISSUE THREAD

**Issue by octadecimal** [avkonst/hookstate#306] opened 2022-07-07 07:39 UTC
Hi Andrey -- 

Thanks for the incredible library. It's what originally made React palatable for me when I started using Hookstate nearly 2 years ago.

I've run into an issue that may be a bug, or more likely a fundamental misunderstanding on my part. I'm hoping you can shed some light on what is wrong here. I've set up a simple CRA that you may clone and reference for your convenience: 

**project**: https://github.com/octadecimal/hookstate-update
**file**: https://github.com/octadecimal/hookstate-update/blob/master/src/App.tsx

### Environment
**React**: 18.2.0
**Hookstate**: 4.0.0-rc11

### Scenario

- A button, when clicked, will add an item to a stateful dictionary: `items`.
- All `items` are rendered as a `div`.
- When an item's `div` is clicked, its `type` property updates to a new, random value.

### Expected/Observed Behavior

- Adding items
  - **Expected**: When a new item is added, the `App` component re-renders, displaying the newly added item.
  - **Observed**: The `App` component isn't re-rendered upon an initial addition of an item, but re-renders for every subsequent added item.

- Clicking/Updating Item
  - **Expected**: When an item is clicked, its `type` field updates, causing a re-render.
  - **Observed**: Initially clicking an item after it's created doesn't cause a re-render, but subsequent clicks do.

![hookstate](https://user-images.githubusercontent.com/172932/177721581-ca01ae2b-dde9-4469-aa18-91955e3a10ee.gif)

Given the fundamental and simple scenario of this, I can't but help but to think I'm doing something terribly wrong. However, I've hit a wall and am hoping you can assist. Many thanks in advance!

**Comment by avkonst** [comment] 2022-07-09 04:42
This is because React 18 introduced this thing to the strict mode. https://reactjs.org/docs/strict-mode.html#ensuring-reusable-state They unmount the component but do not destroy the state. Hookstate assumes that unmounting a component means the same state is never reused again and is actually destroyed. Some plugins rely on destroy to release the resources, like close websocket, remove subscriptions, etc... This is bizar what Facebook is doing...

**Comment by avkonst** [comment] 2022-07-09 05:33
duplicate of #305

**Comment by avkonst** [comment] 2022-07-09 05:34
Thanks for the reproducer. I confirm it is the duplicate report, but thanks yours example helped me to debug it faster and realize the relation to the strict mode.

**Closed by avkonst** 2022-07-09 05:33 UTC
Labels: enhancement

**Comment by avkonst** [comment] 2022-07-09 19:40
Fixed in @hookstate/core@4.0.0-rc12, please verify

**Comment by octadecimal** [comment] 2022-07-10 09:10
Confirmed fixed in `4.0.0-rc12`. 👍 

Thank you very much for your speedy reply and the time you spent to investigate and fix this!
