### ISSUE TITLE
Use with React Native / Expo

### ISSUE THREAD

**Issue by RCNNT-Industries** [avkonst/hookstate#29] opened 2020-01-06 20:58 UTC
Attempting to log statelinks yields an error, which is troublesome when trying to debug

```console.error: "There was a problem sending log messages to your development environment", {"line":127542,"column":25,"sourceURL":"http://127.0.0.1:19001/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&minify=false&hot=false"}```

**Comment by avkonst** [comment] 2020-01-06 21:21
Could you please give more information about the use case you have got and why you think it is a problem with hookstate? I am not familiar with the native ios development and can not event guess what / how you use hookstate to cause this problem...

**Comment by praisethemoon** [comment] 2020-01-07 07:07
@RCNNT-Industries does hookstate it self works fine (without any plugins) on React Native? I agree that logs are very important as well. And supporting react native 100% would be neat!

**Comment by avkonst** [comment] 2020-01-07 07:18
Core library should work fine as it uses almost only React.useState and React.useEffect functionality. Logger plugin may be not done properly to be compliant with ios native, but I am not sure what can be fixed in the logger. The logger only uses `console.log()`. Can it cause problems? should console be banned for native ios app?

**Comment by praisethemoon** [comment] 2020-01-07 07:39
I just did a google search and turns out this error appears frequently, have a look at this: https://stackoverflow.com/questions/54174761/react-native-problem-sending-log-console-error

Seems to me it appears when sending raw objects the error happens. But sending stringified versions works. This happens internally in hookstate log plugin so testing it would be tricky. 

Again I am not sure that this is 100% the cause.

**Comment by avkonst** [comment] 2020-01-07 08:18
> Seems to me it appears when sending raw objects the error happens.

If it is the case, the Logger plugin can be fixed to avoid putting raw objects to the console. Is there any way to detect in a library if it is Native or not-Native environment? Or should we add global setting to the Logger to tune it's behaviour?

**Comment by avkonst** [comment] 2020-01-30 03:06
@RCNNT-Industries could you please verify if the root cause is in logger sending raw objects?

**Comment by avkonst** [comment] 2020-03-04 05:51
Logger plugin is going to be deprecated in favour of @hookstate/devtools. See https://github.com/avkonst/hookstate/issues/38

**Closed by avkonst** 2020-03-04 05:51 UTC
Labels: bug, invalid, question
