### ISSUE TITLE
React Dev Tools crashes due to useState naming conflict.

### ISSUE THREAD

**Issue by Singha360** [avkonst/hookstate#123] opened 2021-01-15 21:24 UTC
As per what the title says...

I've tried with this:

```js
import React from "react";
import { useState } from "@hookstate/core";

import { state } from "./globalState";

function Counter() {
	const counter = useState(state);
	// const test = useState(0);

	const onClick = () => {
		counter.set((value: number) => (value += 1));
	};

	return (
		<div className="Counter">
			<h1>{counter.value}</h1>
			<button onClick={onClick}>Click to Add</button>
			{/* <h1>{test.value}</h1> */}
		</div>
	);
}

export default Counter;

```

If I uncomment the _test_ state I get errors on the console and the components information doesn't load in the React Dev Tools tab.

This how it looks like when I comment the _test_ state line and the corresponding _h1_ tag:
![Screenshot from 2021-01-15 16-17-56](https://user-images.githubusercontent.com/35334787/104779796-b8d50a80-574d-11eb-92fe-8c94c0cddae5.png)

And here is when I use two _useState_ in one component:
![Screenshot from 2021-01-15 16-18-15](https://user-images.githubusercontent.com/35334787/104779799-b8d50a80-574d-11eb-8208-2e5b99a91750.png)
![Screenshot from 2021-01-15 16-19-10](https://user-images.githubusercontent.com/35334787/104779800-b96da100-574d-11eb-91ba-cbbf17eec07c.png)

Here's the list of dependencies on my _package.json_:
```json
"dependencies": {
    "@hookstate/core": "^3.0.3",
    "react": "^17.0.1",
    "react-dom": "^17.0.1"
  }
```

[On the hookstate's website, it says that _useState_ can be used more than once ](https://hookstate.js.org/docs/typedoc-hookstate-core#usestate): 

> A component can use one or many states, i.e. you may call useState multiple times for multiple states.

**Comment by avkonst** [comment] 2021-01-17 23:38
Correct the state hook can be used more than once.

This bug is a bug in the react development tools. I managed to reproduce it by simply adding the following line:
```
const testState = React.useState(0); // please NOTICE, this is plain react state hook!
```
to the demo application: https://github.com/avkonst/hookstate/tree/master/docs/demos/todolist
![image](https://user-images.githubusercontent.com/3971413/104859365-af37e680-5989-11eb-8ad8-2b9923dcbfeb.png)

Interestingly that the bug does not appear if I swap the lines:
![image](https://user-images.githubusercontent.com/3971413/104859385-da223a80-5989-11eb-932c-4af21d68c53b.png)

Would you be able to report this bug to react developers?

**Comment by Singha360** [comment] 2021-01-18 03:21
The thing is, this seems more like a _Hookstate_ issue since using the `React.useState` hook more than once in a component seems to work completely fine. I can observe every states within the DevTools:

![Screenshot from 2021-01-17 22-08-51](https://user-images.githubusercontent.com/35334787/104868249-dc947e00-5910-11eb-8e21-05750b42c57b.png)


Therefore, I am not sure if reporting this bug to the React devs is a good idea currently.

Although, I'll try to find time to look more into it and keep you posted if I find anything.

**Comment by avkonst** [comment] 2021-01-18 04:24
Yes, it works with plain state hooks because the state values are quire simple values. Hookstate.useState wraps 2 hooks - React.useState and React.useEffect (you can see it in the devtools when it does not catch this bug), but the state value is complex value, which the devtool struggles with in the case you discovered. The call stack of an error points to the devtools code. The crash is somewhere within the devtools. And I think it is relatively recent issue as I have not seen it before and I am sure I used more than one state hook in many places.

**Comment by Singha360** [comment] 2021-01-18 10:35
Ah! I was under the impression that this bug hasn't been catch before and was always there. But since you said this came out recently I suppose it is reasonable to open an issue to the react devs.

**Comment by avkonst** [comment] 2021-01-18 21:46
The main reason to open it for react devs is because the crash happens in
their code... And yes, I have not seen it before but maybe it was there and
I did not pay attention..

**Comment by Singha360** [comment] 2021-01-18 23:45
@avkonst This issue seems to be out of scope for the React Dev teams. https://github.com/facebook/react/issues/20609#issuecomment-762513604:

> @Singha360 thanks for the info!
> 
> I'm going to close this until there's a vanilla React reproduction case since, as you said, this works when using just React hooks.

Looking at this, is there anything that throws you off? Something that might cause this issue? :
![image](https://user-images.githubusercontent.com/35334787/104971574-305ca100-59bd-11eb-948b-4f311a7fbf60.png)

**Comment by avkonst** [comment] 2021-01-19 00:16
This code is good. If statements here are robust and have got 100% coverage by tests.

**Comment by avkonst** [comment] 2021-01-19 00:16
I will take over the issue you reported to react.

**Comment by avkonst** [comment] 2021-01-19 01:52
reported the same issue without hookstate: 
https://github.com/facebook/react/issues/20613

**Comment by TroyJoachim** [comment] 2021-02-12 03:48
It doesn't seem like the React team is in a hurry to fix the issue, so I created a temporary fork where I changed the name from useState to useHookstate, so that I can use the devtools for the time being. 

If anyone wants to use it feel free: [TroyJoachim/hookstate](https://github.com/TroyJoachim/hookstate) 
You can install it with "npm install TroyJoachim/hookstate".

**Comment by avkonst** [comment] 2021-02-12 05:02
There is a progress by react team. Their latest update on the pull request suggesting the fix was 2 days ago and is under development for 2-3 now.

**Comment by avkonst** [comment] 2021-02-12 05:12
I have released 3.0.5 with the same workaround

**Comment by avkonst** [comment] 2021-02-12 05:12
It support both useState and useHookstate

**Comment by avkonst** [comment] 2022-05-28 00:27
Hookstate-4 will deprecate useState function because this issue has not been addressed by React team

**Closed** 2022-06-27 09:26 UTC
Labels: question, plugin, hookstate-4
