### ISSUE TITLE
Support for types other then JS primitives properties?

### ISSUE THREAD

**Issue by TroyJoachim** [avkonst/hookstate#124] opened 2021-01-24 20:53 UTC
I tried to save a [File](https://developer.mozilla.org/en-US/docs/Web/API/File) type in state but ran into issue when I tried to use that value by [appending](https://developer.mozilla.org/en-US/docs/Web/API/FormData/append) it to the FormData type. 

`Failed to execute 'append' on 'FormData': parameter 2 is not of type 'Blob'.`

I found that Hookstate was somehow changing the type . Then I read this: https://hookstate.js.org/docs/nested-state/#limitations-for-state-values

I was able to get it to work using React Hooks. Will there be support for types other then JS primitives in the future?

**Comment by avkonst** [comment] 2021-01-27 20:36
I think you can opt-in to the support of File and other complex types by attaching `Downgraded` plugin to the state value, which you do not want to be wrapped in proxy by Hookstate. If you give me more complete example, I will be able to point where to attach the plugin.

Automatic attachment of `Downgraded` plugin to state values of predefined/configurable set of types is theoretically possible, however it might cause problems for plugins which rely on serialization and deserialization of a state object.... Maybe this conflict can be documented somewhere... Let me know what you think about it....

**Comment by avkonst** [comment] 2021-01-29 01:02
Closing as duplicate of https://github.com/avkonst/hookstate/issues/106

**Closed** 2021-01-29 01:02 UTC
Labels: duplicate, enhancement
