### ISSUE TITLE
Document the stores registry pattern

### ISSUE THREAD

**Issue by vbuch** [avkonst/hookstate#299] opened 2022-06-23 10:06 UTC
Hi @avkonst and contributors,
Really hate when people start their silly questions with "first of all thank you for the great lib", but... it's true, so

First of all thank you for the great lib!

This is not a bug report but rather a (silly?) question. "Is it supposed to work this way?"

I have a Map-like state that is initialized as an empty object {}.
Keys are then added to it. state['new-key-1'].set('value');
Whenever that set above is done, all usages of state get rerendered.
I have created a simple repro here https://codepen.io/vbuch/pen/poaXYgZ?editors=0011 where you can observe the above.

Accessor1 is getting rerendered/called on every hit to the "Add more" button.
Accessor2 is not.

I would imagine that the access that Accessor1 does won't be tracked as usage hence won't force a rerender, but... I may be missing something.

Thank you in advance!

**Comment by vbuch** [comment] 2022-06-23 11:02
Thank you for the quick reply! It is indeed a hard one, I understand. Here is a usecase:

1. I have items that are coming occasionally (ref: just as if the "Add more" button is clicked.
2. I only want to show a selected one (ref: like 'SOMETHING THAT IS NOT EVEN IN THE REPO') in a component. (the rest may be shown in other instances of the same component or in other components).
3. The items get occasional updates

I have thought of a possible approach that will not force rerenders but that requires duplicating the selected item in a separate state/member of state. That becomes tricky with the third point above.
I do think that the approach of having a repository that is the single source of truth would be optimal (ref: the way we've set up the whole example) but as it is not possible, do you have any suggestion on how we can work around that?

I've experimented with an array, but then I need to access repo.keys whenever I want to find an item, therefore I will again force render because I'm accessing keys.

If I go the state = {repo: {}, selected: {}} and then add to both, I have to make sure I keep both instances repo[id] and selected in sync and that is again... tricky.

I'm out of ideas, so will be greatful if you have some.

**Comment by avkonst** [comment] 2022-07-22 08:35
Thanks, very nice. yes, I used the repository of states in my projects. This approach works.

**Comment by avkonst** [comment] 2022-07-22 08:35
Keep it open to update the docs how to create a repository of states.

**Comment by avkonst** [comment] 2022-07-22 08:37
Also reminder from the above: "track if enumeration of keys or values of an object happened during render and rerender only in this case"

**Comment by avkonst** [comment] 2022-07-23 13:21
Also, somewhat duplicate of https://github.com/avkonst/hookstate/issues/51

**Comment by vbuch** [comment] 2022-07-25 11:50
I think another term was already used somewhere in the docs for that. Let me fetch it.

**Closed** 2022-12-19 02:07 UTC
Labels: enhancement, wontfix, documentation

**Comment by speigg** [comment] 2023-02-14 22:51
>Hi, thanks for the question. Setting new property to a value is equivalent
to adding a property to an object. And so it means the entire object is
changed, so all the nested properties which are used trigger rerender...

@avkonst  I think I'm also running into this issue. Data structure is like this:

```ts
const stateMap = hookstate({
 [id:number]: [] as Array<Item>|null
})
```

when I do `stateMap[id].merge(items)` for a particular id, it causes other nested states to invalidate for other ids, which causes useEffect components to rerender and useEffect hooks to re-run for unrelated items. 

I don't know that a non-tracked registry pattern works for me, since I need to be able to react to the registry itself having items added and removed.

**Comment by vbuch** [comment] 2023-02-15 07:37
@speigg , the way I went around that is:
I have `const repo = new Map([itemId, hookstate(Item)])` and `const items = hookstate([])`. So `items` will allow me hooking to the event of adding items and the `repo` will be the _stores registry_ (as named in the title of the issue) with all the items' data.

**Comment by avkonst** [comment] 2023-02-15 11:34
@speigg what do you mean by "it causes other nested states to invalidate for other ids" ? 
changing one property by merging items to it's array value would make the whole array affected and cause rerender where this array is used. It should not affect other things which do not use the property with the same id

**Comment by speigg** [comment] 2023-02-17 00:08
@vbuch yes, I'm landing on a very similar pattern. something like:
```
const existenceMap = hookstate({} as {[id:string]:true})
const itemMap = new Map<id, State<Item>>()
```

This way, each item in the `itemMap` is tracked (via hookstate) in isolation, without affecting the others, and I can also reactively keep track of when they are added or removed via the `existenceMap`. It's a bit more bookkeeping, but I've got it all abstracted away behind other operations so no big deal. 

>  It should not affect other things which do not use the property with the same id

@avkonst It's a relief to know that's the intention 

> changing one property by merging items to it's array value would make the whole array affected and cause rerender where this array is used. It should not affect other things which do not use the property with the same id

Hard to tell exactly what the cause is, but I am generally seeing undesired/unnecessary component invalidations and state proxies being updated. I might have to create an isolated test case to zero in on the exact mechanism that is causing this behavior, but the only other thing would be items being removed/added from that top level state map, i.e., `stateMap[id].set(items)` where it was previously undefined, or `stateMap[id].set(none)`. Would these operations cause nested items for other ids to invalidate?

**Comment by vbuch** [comment] 2023-02-17 06:56
@speigg adding a new key to `const stateMap = hookstate({key1: 'duh'})` would consider the whole object changed. so `stateMap.key2.set('blah')` will force components using `stateMap.key1.value/get()` to re-render.
