### ISSUE TITLE
Simpler and more intuitive way to do attach(Downgrade)

### ISSUE THREAD

**Issue by bmutafov** [avkonst/hookstate#238] opened 2021-10-01 19:17 UTC
We tried to implement hookstate into our serverless app and we needed to send objects from the state to the firebase database. However, in order to do so, we needed to do the following:
```typescript
const data = myState.attach(Downgraded).get()
```
This has one main issue, which is the reason we scrapped hookstate in favor of something else. It's not intuitive, a person who hasn't read the docs a couple of times won't know what is going on. It's also really counter intuitive how `.get()` returns you a proxy, which can't be used directly in JSON API request. I get that there has to be a reason to force everything to need Downgraded attached to get the pure value, but the way it has to be done is ugly. I suggest creating a function `toObject()` which can attach Downgraded internally, but it just has better code flow. The example from above would become the following:
```typescript
const data = myState.toObject().get()
```
or
```typescript
const data = myState.get().toObject()
```

**Comment by avkonst** [comment] 2021-10-03 22:01
Hi, thanks for the suggestion. Such an API improvement is possible. However, let's root cause the problems first.

"It's also really counter intuitive how .get() returns you a proxy"
Proxy should behave exactly the same as the underlying state value, with an exception of equality operator. Proxy is used for tracking used states of segments to optimize re-rendering.

".get() returns you a proxy, which can't be used directly in JSON API request" Could you please elaborate a bit more? I never had problems with serializing `JSON.stringify(state.get())`.

"everything to need Downgraded attached to get the pure value"
If you always use Downgraded plugin before get, there is something is not right. It is more of an exception than a rule. Also, you can attach Downgraded plugin once to the root state after useState call and have get() returning the original value for the root state and all children states. So no needs to attach downgraded always before get(). Would it work for your usecase?

**Comment by mutafow** [comment] 2021-10-05 13:07
The thing is not that it _doesnt_ work, its just that is sometimes _hard_ to use, especially when refactoring from react state hooks to hookstate. 

> Proxy should behave exactly the same as the underlying state value, with an exception of equality operator

That is true, yes, when using it in React, no issues there, very pleased with the API. However, issues start to appear when you try using that state and sending it to other services. 

For context, we tried converting some global states from react contexts to hookstate

We have many methods which accept objects (usually react states), which then are used in various ways, mainly API calls. When calling those functions with `myState.get()` as parameter instead of the old `myState`, a proxy is passed which then down the line breaks somewhere due to it being a Proxy. So the only straightforward solution was to attach Downgraded plugin before calling `.get()`. JSON.stringify wouldn't work in this scenario as we need the object down the line. And `JSON.parse(JSON.stringify())` is ugly and not working well with TypeScript types unless you put some more effort there.

> Also, you can attach Downgraded plugin once to the root state after useState call and have get() returning the original value for the root state and all children states.

Yes, however that seemed to be not correct by the documentation, as you lose various optimizations. We don't want that because we need to use the pure value N times in some methods, we can just Downgrade it whenever we need it to. And there comes the problem - its not a problem that we have to do it, it is the way it has to be done. It's not easily understandable what it does, unless you go find the documentation and read about it. On top of that, you need another import for the Downgraded plugin, you need to explain to new colleagues what is attach(Downgraded) and why it has to be done and so on. In my opinion its just bad **developer experience**, nothing else.  

It can greatly simplify the learning curve, debugging and docs for such use cases.

**Comment by shimorojune** [comment] 2021-10-18 02:37
@avkonst `origin` is good with me.

A few alternatives would be `raw`, `bare`, or `downgraded` I guess.

Btw the library is freaking awesome! Always a joy to manage state with it!

**Comment by arbob** [comment] 2021-10-21 04:09
> No problems. What would be the best name for the new property? I am thinking of giving it the name `origin`?

I'd vote for a simpler and intuitive `state.value.get()`.

**Comment by avkonst** [comment] 2021-11-15 20:26
> 'd vote for a simpler and intuitive

Unfortunately get() is already reserved. Unless we break backward compatibility this name is impossible

**Comment by gitsome** [comment] 2022-02-13 22:31
+1 on this feature.  Being able to snapshot/serialize state would be a nice addition.

**Comment by stefanoeb** [comment] 2022-02-15 10:45
Yeah that'd be awesome, I vote for `raw` as it does not conflict with anything. Also I believe it would be a function call like `.raw()`? I think it make sense, cuz using getters confuse me on whether I'm simply accessing a value in memory or it's doing "more work"

**Comment by avkonst** [comment] 2022-05-28 00:57
candidates for new State method or property: unwrap, value.get(), data, raw.

**Comment by avkonst** [comment] 2022-05-28 00:57
It will get addressed in Hookstate-4

**Comment by avkonst** [comment] 2022-06-20 12:02
Hookstate 4: State method `get` has options. One of it allows to remove proxy wrapping:
```
let state = useState(...)
state.get({ noproxy: true }) // returns the value state without proxy wrapping
```
New Extensions API allows to add extension methods, so it is easy to add an extension method which would do `get({ noproxy: true })` inside. An extension method or property can have any name, so anything of the following could be possible:

```
let state = useState(..., () => MyExtensionToGetValueWithoutProxy())
// assuming the extension implements the following methods, any name is possible:
state.unwrap()
state.raw()
state.data
///....
```
Documentation updates are pending.

**Closed by avkonst** 2022-06-20 12:02 UTC
Labels: enhancement, question, hookstate-4
